[project]
name = "PdmContext"
version = "0.0.4"
authors = [
  { name="Apostolos Giannoulidis", email="agiannous@csd.auth.gr" },
]
description = "Context is used here to provide a better understanding of the difference cases the data are each time. Essentially, Context represent the data (CD), existing in a time window, and their relationships (CR), where the relationships are extracted using causal discovery between the data (the causal discovery method can be user defiend)."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[project.urls]
Homepage = "https://github.com/agiannoul/PdMContext"
Issues = "https://github.com/agiannoul/PdMContext/issues"
documentation = "https://pd-m-context.vercel.app/"